/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.102
 * Generated at: 2025-04-10 05:59:19 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class MainForm_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(4);
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP 只允许 GET、POST 或 HEAD。Jasper 还允许 OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"utf-8\">\r\n");
      out.write("<title>Demo</title>\r\n");
      out.write("<meta name=\"renderer\" content=\"webkit\">\r\n");
      out.write("<meta http-equiv=\"X-UA-Compatible\" content=\"IE=edge,chrome=1\">\r\n");
      out.write("<meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\r\n");
      out.write("<link href=\".//layui/css/layui.css\" rel=\"stylesheet\">\r\n");
      out.write("<script src=\".//layui/layui.js\"></script>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("	<div class=\"layui-layout layui-layout-admin\">\r\n");
      out.write("		<div class=\"layui-header\">\r\n");
      out.write("			<div class=\"layui-logo layui-hide-xs layui-bg-black\">layout\r\n");
      out.write("				demo</div>\r\n");
      out.write("			<!-- 头部区域（可配合layui 已有的水平导航） -->\r\n");
      out.write("			<ul class=\"layui-nav layui-layout-left\">\r\n");
      out.write("				<!-- 移动端显示 -->\r\n");
      out.write("				<li class=\"layui-nav-item layui-show-xs-inline-block layui-hide-sm\"\r\n");
      out.write("					lay-header-event=\"menuLeft\"><i\r\n");
      out.write("					class=\"layui-icon layui-icon-spread-left\"></i></li>\r\n");
      out.write("				<li class=\"layui-nav-item layui-hide-xs\"><a href=\"javascript:;\">nav\r\n");
      out.write("						1</a></li>\r\n");
      out.write("				<li class=\"layui-nav-item layui-hide-xs\"><a href=\"javascript:;\">nav\r\n");
      out.write("						2</a></li>\r\n");
      out.write("				<li class=\"layui-nav-item layui-hide-xs\"><a href=\"javascript:;\">nav\r\n");
      out.write("						3</a></li>\r\n");
      out.write("				<li class=\"layui-nav-item\"><a href=\"javascript:;\">nav\r\n");
      out.write("						groups</a>\r\n");
      out.write("					<dl class=\"layui-nav-child\">\r\n");
      out.write("						<dd>\r\n");
      out.write("							<a href=\"javascript:;\">menu 11</a>\r\n");
      out.write("						</dd>\r\n");
      out.write("						<dd>\r\n");
      out.write("							<a href=\"javascript:;\">menu 22</a>\r\n");
      out.write("						</dd>\r\n");
      out.write("						<dd>\r\n");
      out.write("							<a href=\"javascript:;\">menu 33</a>\r\n");
      out.write("						</dd>\r\n");
      out.write("					</dl></li>\r\n");
      out.write("			</ul>\r\n");
      out.write("			<ul class=\"layui-nav layui-layout-right\">\r\n");
      out.write("				<li class=\"layui-nav-item layui-hide layui-show-sm-inline-block\">\r\n");
      out.write("					<a href=\"javascript:;\"> <img\r\n");
      out.write("						src=\"//unpkg.com/outeres@0.0.10/img/layui/icon-v2.png\"\r\n");
      out.write("						class=\"layui-nav-img\"> tester\r\n");
      out.write("				</a>\r\n");
      out.write("					<dl class=\"layui-nav-child\">\r\n");
      out.write("						<dd>\r\n");
      out.write("							<a href=\"javascript:;\">Your Profile</a>\r\n");
      out.write("						</dd>\r\n");
      out.write("						<dd>\r\n");
      out.write("							<a href=\"javascript:;\">Settings</a>\r\n");
      out.write("						</dd>\r\n");
      out.write("						<dd>\r\n");
      out.write("							<a href=\"javascript:;\">Sign out</a>\r\n");
      out.write("						</dd>\r\n");
      out.write("					</dl>\r\n");
      out.write("				</li>\r\n");
      out.write("				<li class=\"layui-nav-item\" lay-header-event=\"menuRight\" lay-unselect>\r\n");
      out.write("					<a href=\"javascript:;\"> <i\r\n");
      out.write("						class=\"layui-icon layui-icon-more-vertical\"></i>\r\n");
      out.write("				</a>\r\n");
      out.write("				</li>\r\n");
      out.write("			</ul>\r\n");
      out.write("		</div>\r\n");
      out.write("		<div class=\"layui-side layui-bg-black\">\r\n");
      out.write("			<div class=\"layui-side-scroll\">\r\n");
      out.write("				<!-- 左侧导航区域（可配合layui已有的垂直导航） -->\r\n");
      out.write("				<ul class=\"layui-nav layui-nav-tree\" lay-filter=\"test\">\r\n");
      out.write("					<li class=\"layui-nav-item layui-nav-itemed\"><a class=\"\"\r\n");
      out.write("						href=\"javascript:;\">menu group 1</a>\r\n");
      out.write("						<dl class=\"layui-nav-child\">\r\n");
      out.write("							<dd>\r\n");
      out.write("								<a href=\"javascript:;\">menu 1</a>\r\n");
      out.write("							</dd>\r\n");
      out.write("							<dd>\r\n");
      out.write("								<a href=\"javascript:;\">menu 2</a>\r\n");
      out.write("							</dd>\r\n");
      out.write("							<dd>\r\n");
      out.write("								<a href=\"javascript:;\">menu 3</a>\r\n");
      out.write("							</dd>\r\n");
      out.write("							<dd>\r\n");
      out.write("								<a href=\"javascript:;\">the links</a>\r\n");
      out.write("							</dd>\r\n");
      out.write("						</dl></li>\r\n");
      out.write("					<li class=\"layui-nav-item\"><a href=\"javascript:;\">menu\r\n");
      out.write("							group 2</a>\r\n");
      out.write("						<dl class=\"layui-nav-child\">\r\n");
      out.write("							<dd>\r\n");
      out.write("								<a href=\"javascript:;\">list 1</a>\r\n");
      out.write("							</dd>\r\n");
      out.write("							<dd>\r\n");
      out.write("								<a href=\"javascript:;\">list 2</a>\r\n");
      out.write("							</dd>\r\n");
      out.write("							<dd>\r\n");
      out.write("								<a href=\"javascript:;\">超链接</a>\r\n");
      out.write("							</dd>\r\n");
      out.write("						</dl></li>\r\n");
      out.write("					<li class=\"layui-nav-item\"><a href=\"javascript:;\">click\r\n");
      out.write("							menu item</a></li>\r\n");
      out.write("					<li class=\"layui-nav-item\"><a href=\"javascript:;\">the\r\n");
      out.write("							links</a></li>\r\n");
      out.write("				</ul>\r\n");
      out.write("			</div>\r\n");
      out.write("		</div>\r\n");
      out.write("		<div class=\"layui-body\">\r\n");
      out.write("			<!-- 内容主体区域 -->\r\n");
      out.write("			<div style=\"padding: 15px;\">\r\n");
      out.write("				<blockquote class=\"layui-elem-quote layui-text\">Layui\r\n");
      out.write("					框体布局内容主体区域</blockquote>\r\n");
      out.write("				<div class=\"layui-card layui-panel\">\r\n");
      out.write("					<div class=\"layui-card-header\">下面是充数内容，为的是出现滚动条</div>\r\n");
      out.write("					<div class=\"layui-card-body\">\r\n");
      out.write("						充数内容<br>充数内容<br>充数内容<br>充数内容<br>充数内容<br>充数内容<br>充数内容<br>充数内容<br>充数内容<br>充数内容<br>充数内容<br>充数内容<br>充数内容<br>充数内容<br>充数内容<br>充数内容<br>充数内容<br>充数内容<br>充数内容<br>充数内容<br>充数内容<br>充数内容<br>充数内容<br>充数内容<br>充数内容<br>充数内容<br>充数内容<br>充数内容<br>充数内容<br>充数内容<br>充数内容<br>充数内容<br>充数内容<br>充数内容<br>充数内容<br>充数内容<br>充数内容<br>充数内容<br>充数内容<br>充数内容<br>充数内容<br>充数内容<br>充数内容<br>充数内容<br>充数内容<br>充数内容<br>充数内容<br>充数内容<br>充数内容<br>充数内容<br>你还真滑到了底部呀\r\n");
      out.write("					</div>\r\n");
      out.write("				</div>\r\n");
      out.write("				<br>\r\n");
      out.write("				<br>\r\n");
      out.write("			</div>\r\n");
      out.write("		</div>\r\n");
      out.write("		<div class=\"layui-footer\">\r\n");
      out.write("			<!-- 底部固定区域 -->\r\n");
      out.write("			底部固定区域\r\n");
      out.write("		</div>\r\n");
      out.write("	</div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("	<script>\r\n");
      out.write("//JS \r\n");
      out.write("	layui.use([ 'element', 'layer', 'util' ], function() {\r\n");
      out.write("		var element = layui.element;\r\n");
      out.write("		var layer = layui.layer;\r\n");
      out.write("		var util = layui.util;\r\n");
      out.write("		var $ = layui.$;\r\n");
      out.write("\r\n");
      out.write("		//头部事件\r\n");
      out.write("		util.event('lay-header-event', {\r\n");
      out.write("			menuLeft : function(othis) { // 左侧菜单事件\r\n");
      out.write("				layer.msg('展开左侧菜单的操作', {\r\n");
      out.write("					icon : 0\r\n");
      out.write("				});\r\n");
      out.write("			},\r\n");
      out.write("			menuRight : function() { // 右侧菜单事件\r\n");
      out.write("				layer.open({\r\n");
      out.write("					type : 1,\r\n");
      out.write("					title : '更多',\r\n");
      out.write("					content : '<div style=\"padding: 15px;\">处理右侧面板的操作</div>',\r\n");
      out.write("					area : [ '260px', '100%' ],\r\n");
      out.write("					offset : 'rt', // 右上角\r\n");
      out.write("					anim : 'slideLeft', // 从右侧抽屉滑出\r\n");
      out.write("					shadeClose : true,\r\n");
      out.write("					scrollbar : false\r\n");
      out.write("				});\r\n");
      out.write("			}\r\n");
      out.write("		});\r\n");
      out.write("	});\r\n");
      out.write("</script>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
