/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.102
 * Generated at: 2025-04-09 15:01:41 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class Register_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(4);
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP 只允许 GET、POST 或 HEAD。Jasper 还允许 OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"utf-8\">\r\n");
      out.write("<meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\r\n");
      out.write("<title>Demo</title>\r\n");
      out.write("<link href=\".//layui/css/layui.css\" rel=\"stylesheet\">\r\n");
      out.write("<script src=\".//layui/layui.js\"></script>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("	<style>\r\n");
      out.write(".demo-reg-container {\r\n");
      out.write("	width: 320px;\r\n");
      out.write("	margin: 21px auto 0;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".demo-reg-other .layui-icon {\r\n");
      out.write("	position: relative;\r\n");
      out.write("	display: inline-block;\r\n");
      out.write("	margin: 0 2px;\r\n");
      out.write("	top: 2px;\r\n");
      out.write("	font-size: 26px;\r\n");
      out.write("}\r\n");
      out.write("</style>\r\n");
      out.write("	<form class=\"layui-form\">\r\n");
      out.write("		<div class=\"demo-reg-container\">\r\n");
      out.write("			<div class=\"layui-form-item\">\r\n");
      out.write("				<div class=\"layui-input-wrap\">\r\n");
      out.write("					<div class=\"layui-input-prefix\">\r\n");
      out.write("						<i class=\"layui-icon layui-icon-password\"></i>\r\n");
      out.write("					</div>\r\n");
      out.write("					<input type=\"password\" name=\"password\" value=\"\"\r\n");
      out.write("						lay-verify=\"required\" placeholder=\"密码\" autocomplete=\"off\"\r\n");
      out.write("						class=\"layui-input\" id=\"reg-password\" lay-affix=\"eye\">\r\n");
      out.write("				</div>\r\n");
      out.write("			</div>\r\n");
      out.write("			<div class=\"layui-form-item\">\r\n");
      out.write("				<div class=\"layui-input-wrap\">\r\n");
      out.write("					<div class=\"layui-input-prefix\">\r\n");
      out.write("						<i class=\"layui-icon layui-icon-password\"></i>\r\n");
      out.write("					</div>\r\n");
      out.write("					<input type=\"password\" name=\"confirmPassword\" value=\"\"\r\n");
      out.write("						lay-verify=\"required|confirmPassword\" placeholder=\"确认密码\"\r\n");
      out.write("						autocomplete=\"off\" class=\"layui-input\" lay-affix=\"eye\">\r\n");
      out.write("				</div>\r\n");
      out.write("			</div>\r\n");
      out.write("			<div class=\"layui-form-item\">\r\n");
      out.write("				<div class=\"layui-input-wrap\">\r\n");
      out.write("					<div class=\"layui-input-prefix\">\r\n");
      out.write("						<i class=\"layui-icon layui-icon-email\"></i>\r\n");
      out.write("					</div>\r\n");
      out.write("					<input type=\"text\" name=\"email\" value=\"\" lay-verify=\"required\"\r\n");
      out.write("						placeholder=\"邮箱\" autocomplete=\"off\" class=\"layui-input\"\r\n");
      out.write("						lay-affix=\"clear\">\r\n");
      out.write("				</div>\r\n");
      out.write("			</div>\r\n");
      out.write("			<div class=\"layui-form-item\">\r\n");
      out.write("				<div class=\"layui-input-wrap\">\r\n");
      out.write("					<div class=\"layui-input-prefix\">\r\n");
      out.write("						<i class=\"layui-icon layui-icon-username\"></i>\r\n");
      out.write("					</div>\r\n");
      out.write("					<input type=\"text\" name=\"name\" value=\"\" lay-verify=\"required\"\r\n");
      out.write("						placeholder=\"昵称\" autocomplete=\"off\" class=\"layui-input\"\r\n");
      out.write("						lay-affix=\"clear\">\r\n");
      out.write("				</div>\r\n");
      out.write("			</div>\r\n");
      out.write("			<div class=\"layui-form-item\">\r\n");
      out.write("				<input type=\"checkbox\" name=\"agreement\" lay-verify=\"required\"\r\n");
      out.write("					lay-skin=\"primary\" title=\"同意\"> <a href=\"#terms\"\r\n");
      out.write("					target=\"_blank\" style=\"position: relative; top: 6px; left: -15px;\">\r\n");
      out.write("					<ins>用户协议</ins>\r\n");
      out.write("				</a>\r\n");
      out.write("			</div>\r\n");
      out.write("			<div class=\"layui-form-item\">\r\n");
      out.write("				<button class=\"layui-btn layui-btn-fluid\" lay-submit\r\n");
      out.write("					lay-filter=\"demo-reg\">注册</button>\r\n");
      out.write("			</div>\r\n");
      out.write("			<div class=\"layui-form-item demo-reg-other\">\r\n");
      out.write("				<a href=\"LoginServlet\">登录已有帐号</a>\r\n");
      out.write("			</div>\r\n");
      out.write("		</div>\r\n");
      out.write("	</form>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("	<script>\r\n");
      out.write("		layui.use(function() {\r\n");
      out.write("			var $ = layui.$;\r\n");
      out.write("			var form = layui.form;\r\n");
      out.write("			var layer = layui.layer;\r\n");
      out.write("			var util = layui.util;\r\n");
      out.write("			// 自定义验证规则\r\n");
      out.write("			form.verify({\r\n");
      out.write("				// 确认密码\r\n");
      out.write("				confirmPassword : function(value, item) {\r\n");
      out.write("					var passwordValue = $('#reg-password').val();\r\n");
      out.write("					if (value !== passwordValue) {\r\n");
      out.write("						return '两次密码输入不一致';\r\n");
      out.write("					}\r\n");
      out.write("				}\r\n");
      out.write("			});\r\n");
      out.write("\r\n");
      out.write("			// 提交事件\r\n");
      out.write("			form.on('submit(demo-reg)', function(data) {\r\n");
      out.write("				// 获取表单字段值\r\n");
      out.write("				var name = data.field.name;\r\n");
      out.write("				var password = data.field.password;\r\n");
      out.write("				//var email = data.field.email;\r\n");
      out.write("				console.log(JSON.stringify(data.field));\r\n");
      out.write("				// 是否勾选同意\r\n");
      out.write("				if (!data.field.agreement) {\r\n");
      out.write("					layer.msg('您必须勾选同意用户协议才能注册');\r\n");
      out.write("					return false;\r\n");
      out.write("				}\r\n");
      out.write("				$.ajax({\r\n");
      out.write("					url : '/javaweb/CheckRegisterServlet',//通讯地址\r\n");
      out.write("					type : 'post',//get或者post \r\n");
      out.write("					data : {\r\n");
      out.write("						'name' : name,\r\n");
      out.write("						'password' : password\r\n");
      out.write("					},//发送到服务端的数据K-V形式\r\n");
      out.write("					dataType : \"text\",//接收到的数据的类型可以是json或者text\r\n");
      out.write("					success : function(res) {\r\n");
      out.write("						if (res === \"success\") {\r\n");
      out.write("							layer.alert(\"操作成功\");\r\n");
      out.write("						} else if (res === \"user exists\") {\r\n");
      out.write("							layer.alert(\"用户已存在\");\r\n");
      out.write("						} else {\r\n");
      out.write("							layer.alert(\"操作失败\");\r\n");
      out.write("						}\r\n");
      out.write("					}\r\n");
      out.write("				});\r\n");
      out.write("\r\n");
      out.write("				return false; // 阻止默认 form 跳转\r\n");
      out.write("			});\r\n");
      out.write("		});\r\n");
      out.write("	</script>\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
