/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.102
 * Generated at: 2025-04-15 14:26:11 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class errorInfo_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(4);
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    java.lang.Throwable exception = org.apache.jasper.runtime.JspRuntimeLibrary.getThrowable(request);
    if (exception != null) {
      response.setStatus(javax.servlet.http.HttpServletResponse.SC_INTERNAL_SERVER_ERROR);
    }
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"utf-8\">\r\n");
      out.write("<title>404 é¡µé¢ä¸å­å¨</title>\r\n");
      out.write("<meta name=\"renderer\" content=\"webkit\">\r\n");
      out.write("<meta http-equiv=\"X-UA-Compatible\" content=\"IE=edge,chrome=1\">\r\n");
      out.write("<meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"/layui/css/layui.css\" media=\"all\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"/layui/admin.css\" media=\"all\">\r\n");
      out.write("<script src=\"/layui/layui.js\"></script>\r\n");
      out.write("\r\n");
      out.write("</head>\r\n");
      out.write("<body layadmin-themealias=\"default\">\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("	<div class=\"layui-fluid\">\r\n");
      out.write("		<div class=\"layadmin-tips\">\r\n");
      out.write("			<i class=\"layui-icon\" face=\"\">î¤</i>\r\n");
      out.write("			<div class=\"layui-text\">\r\n");
      out.write("				<h1>\r\n");
      out.write("					<span class=\"layui-anim layui-anim-loop layui-anim-\">4</span> <span\r\n");
      out.write("						class=\"layui-anim layui-anim-loop layui-anim-rotate\">0</span> <span\r\n");
      out.write("						class=\"layui-anim layui-anim-loop layui-anim-\">4</span>\r\n");
      out.write("				</h1>\r\n");
      out.write("			</div>\r\n");
      out.write("		</div>\r\n");
      out.write("	</div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("	<script>\r\n");
      out.write("		layui.config({\r\n");
      out.write("			base : '../../../res/' // éæèµæºæå¨è·¯å¾\r\n");
      out.write("		}).use([ 'index' ]);\r\n");
      out.write("	</script>\r\n");
      out.write("	<!-- Cloudflare Pages Analytics -->\r\n");
      out.write("	<script defer=\"\"\r\n");
      out.write("		src=\"https://static.cloudflareinsights.com/beacon.min.js\"\r\n");
      out.write("		data-cf-beacon=\"{&quot;token&quot;: &quot;43b4b1a48ab04f89a979a2c4f6be6118&quot;}\"></script>\r\n");
      out.write("	<!-- Cloudflare Pages Analytics -->\r\n");
      out.write("	<style id=\"LAY_layadmin_theme\">\r\n");
      out.write(".layui-side-menu, .layui-layer-admin .layui-layer-title,\r\n");
      out.write("	.layadmin-side-shrink .layui-side-menu .layui-nav>.layui-nav-item>.layui-nav-child\r\n");
      out.write("	{\r\n");
      out.write("	background-color: #20222A !important;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".layadmin-pagetabs .layui-tab-title li:after, .layadmin-pagetabs .layui-tab-title li.layui-this:after,\r\n");
      out.write("	.layui-nav-tree .layui-this, .layui-nav-tree .layui-this>a,\r\n");
      out.write("	.layui-nav-tree .layui-nav-child dd.layui-this, .layui-nav-tree .layui-nav-child dd.layui-this a,\r\n");
      out.write("	.layui-nav-tree .layui-nav-bar {\r\n");
      out.write("	background-color: #16baaa !important;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".layadmin-pagetabs .layui-tab-title li:hover, .layadmin-pagetabs .layui-tab-title li.layui-this\r\n");
      out.write("	{\r\n");
      out.write("	color: #16baaa !important;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".layui-layout-admin .layui-logo {\r\n");
      out.write("	background-color: #20222A !important;\r\n");
      out.write("}\r\n");
      out.write("</style>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
